name: Publish Progress Reporting

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  pull_request:
    types: [closed]
    branches: [ "master" ]
    paths: 
      - './**/progressReporting.csproj'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  Project: './progressReporting/progressReporting.csproj'
  DotNetVersion: 7.0.x

defaults:
  run:
    working-directory: .

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DotNetVersion }}
      - uses: tedd/publish-nuget-neo@v1
        with:
          NUGET_KEY: ${{secrets.NEW_COMMAND_VERSION}}
          PROJECT_FILE_PATH: ${{env.Project}}
          TAG_COMMIT: true
